# Generated by Django 5.0.2 on 2025-12-10 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('almacen_id_msip', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo_web', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraSincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('articulos_procesados', models.IntegerField(default=0)),
                ('articulos_creados', models.IntegerField(default=0)),
                ('articulos_actualizados', models.IntegerField(default=0)),
                ('articulos_desactivados', models.IntegerField(default=0)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('EXITO', 'Éxito'), ('ERROR', 'Error')], default='EN_PROCESO', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('articulo_id_msip', models.IntegerField(db_index=True, unique=True, verbose_name='ID MSIP')),
                ('clave', models.CharField(db_index=True, help_text='Clave Principal (Rol 17)', max_length=50, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('costo_ultimo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('precio_lista', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('seguimiento_tipo', models.CharField(choices=[('N', 'Normal'), ('L', 'Lotes'), ('S', 'Series')], default='N', max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'indexes': [models.Index(fields=['nombre', 'activo'], name='capturador__nombre_4435b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha_captura', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('PROCESADO', 'Procesado')], default='BORRADOR', max_length=20)),
                ('detalles_texto', models.TextField(blank=True, null=True)),
                ('modo_offline', models.BooleanField(default=False)),
                ('fecha_reportada', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capturador_inventario_api.almacen')),
                ('capturador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave_interna', models.CharField(blank=True, help_text='ID de trabajador o Clave Admin en Microsip', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('puesto', models.CharField(choices=[('ADMIN', 'Administrador'), ('CAPTURADOR', 'Capturador de Almacén'), ('OTRO', 'Otro Empleado')], default='CAPTURADOR', max_length=50)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaveAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=50)),
                ('rol_clave_msip', models.IntegerField(default=18)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves_auxiliares', to='capturador_inventario_api.articulo')),
            ],
            options={
                'verbose_name': 'Clave Auxiliar',
                'verbose_name_plural': 'Claves Auxiliares',
                'unique_together': {('articulo', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.DecimalField(decimal_places=5, max_digits=18)),
                ('existencia_sistema_al_momento', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('localizacion_al_momento', models.CharField(blank=True, max_length=50, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='capturador_inventario_api.articulo')),
                ('captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='capturador_inventario_api.captura')),
            ],
            options={
                'unique_together': {('captura', 'articulo')},
            },
        ),
        migrations.CreateModel(
            name='InventarioArticulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('localizacion', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Ubicación')),
                ('existencia', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('stock_minimo', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('stock_maximo', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('punto_reorden', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('pendiente_sincronizar_msip', models.BooleanField(default=False, help_text='True si se editó localmente y falta enviar a Microsip')),
                ('fecha_ultima_modificacion_local', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='capturador_inventario_api.almacen')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias_almacen', to='capturador_inventario_api.articulo')),
            ],
            options={
                'verbose_name': 'Inventario por Almacén',
                'indexes': [models.Index(fields=['articulo', 'almacen'], name='capturador__articul_3aa06e_idx')],
                'unique_together': {('articulo', 'almacen')},
            },
        ),
    ]
