# Generated by Django 5.0.2 on 2025-11-10 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave_admin', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado')], default='PROGRESO', max_length=10)),
                ('capturador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capturadores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_trabajador', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCaptura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('producto_codigo', models.CharField(max_length=100)),
                ('cantidad_contada', models.PositiveIntegerField()),
                ('captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='capturador_inventario_api.captura')),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
