# Generated by Django 5.0.2 on 2025-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(blank=True, help_text='RFC del empleado', max_length=13, null=True),
        ),
    ]
