# Generated by Django 5.0.2 on 2025-12-17 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=255, verbose_name='Persona que retira')),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=18)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='capturador_inventario_api.detallecaptura')),
            ],
        ),
    ]
