# Generated by Django 5.0.2 on 2025-11-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0002_administradores_captura_capturadores_detallecaptura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradores',
            name='rfc',
        ),
        migrations.AddField(
            model_name='administradores',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capturadores',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
