# Generated by Django 5.0.2 on 2025-11-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0003_remove_administradores_rfc_administradores_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('articulo_id_msip', models.IntegerField(db_index=True, unique=True, verbose_name='ID Microsip (ARTICULO_ID)')),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Clave Alfanumérica Microsip')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('seguimiento_tipo', models.CharField(choices=[('N', 'Ninguno (0)'), ('L', 'Lotes (1)'), ('S', 'Series (2)')], default='N', max_length=1, verbose_name='Tipo de Seguimiento')),
                ('ultima_sincronizacion', models.DateTimeField(auto_now=True, verbose_name='Última Sincronización')),
            ],
            options={
                'verbose_name': 'Artículo Microsip',
                'verbose_name_plural': 'Artículos Microsip',
            },
        ),
    ]
