# Generated by Django 5.0.2 on 2025-11-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0004_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='codigo_barras',
        ),
        migrations.CreateModel(
            name='ClaveAuxiliar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, verbose_name='Clave Auxiliar / Código de Barras')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves_auxiliares', to='capturador_inventario_api.articulo')),
            ],
            options={
                'verbose_name': 'Clave Auxiliar',
                'verbose_name_plural': 'Claves Auxiliares',
                'unique_together': {('clave',)},
            },
        ),
    ]
