# Generated by Django 5.0.2 on 2025-11-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0005_remove_articulo_codigo_barras_claveauxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
