# Generated by Django 5.0.2 on 2025-12-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0006_articulo_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSincronizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('articulos_procesados', models.IntegerField(default=0, help_text='Total leídos de Microsip')),
                ('articulos_creados', models.IntegerField(default=0)),
                ('articulos_actualizados', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('EXITO', 'Éxito'), ('ERROR', 'Error')], default='EN_PROCESO', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje / Traceback')),
            ],
            options={
                'verbose_name': 'Bitácora de Sincronización',
                'verbose_name_plural': 'Bitácora de Sincronizaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
