# Generated by Django 5.0.2 on 2025-12-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0007_bitacorasincronizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacorasincronizacion',
            name='articulos_desactivados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitacorasincronizacion',
            name='claves_creadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitacorasincronizacion',
            name='detalles_procesamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Log de Procesamiento / Errores Individuales'),
        ),
        migrations.AlterField(
            model_name='bitacorasincronizacion',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Error General / Traceback'),
        ),
    ]
