# Generated by Django 5.0.2 on 2025-12-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0008_bitacorasincronizacion_articulos_desactivados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacorasincronizacion',
            name='articulos_procesados',
            field=models.IntegerField(default=0, help_text='Leídos de Microsip'),
        ),
        migrations.AlterField(
            model_name='bitacorasincronizacion',
            name='detalles_procesamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Log Detalles'),
        ),
        migrations.AlterField(
            model_name='bitacorasincronizacion',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True, verbose_name='Error Traceback'),
        ),
    ]
