# Generated by Django 5.0.2 on 2025-12-02 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0009_alter_bitacorasincronizacion_articulos_procesados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacorasincronizacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave_interna', models.CharField(blank=True, help_text='ID de trabajador o Clave Admin', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('puesto', models.CharField(choices=[('ADMIN', 'Administrador'), ('CAPTURADOR', 'Capturador de Almacén'), ('OTRO', 'Otro Empleado')], default='CAPTURADOR', max_length=20)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
