# Generated by Django 5.0.2 on 2025-12-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturador_inventario_api', '0011_auto_20251202_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturadores',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administradores',
        ),
        migrations.DeleteModel(
            name='Capturadores',
        ),
    ]
